name: Triggered Rmd templates files update
on:
  repository_dispatch:
    types: [rmd-updated]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.1', bioc: '3.14', cont: "bioconductor/bioconductor_docker:RELEASE_3_14", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
          
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo apt-get install libcurl4-openssl-dev
          sudo apt-get install libv8-dev

      - name: Install dependencies
        run: |
          install.packages(c("BiocManager", "knitcitations"))
          BiocManager::install("Bioconductor/BiocStyle")
          BiocManager::install("tgirke/systemPipeR")
          BiocManager::install("tgirke/systemPipeRdata")
        shell: Rscript {0}

      - name: pull new/edit Rmd
        uses: actions/checkout@v2
      - name: Update hash
        run: |
          bash .github/bash/update_rmd.sh https://github.com/dcassol/srpdata_test.git vignettes/
      - name: Update github
        run: |
          git config --local user.name "dcassol"
          git config --local user.email "danicassol@gmail.com"
          git add -A
          git commit -m "Bot update rmd description files" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

